const mongoose = require('mongoose');
const Schema = mongoose.Schema;
const QuestionSchema = new Schema({
  question1: String,
  answer1: String,
  question2: String,
  answer2: String,
  question3: String,
  answer3: String,
  question4: String,
  answer4: String,
  question5: String,
  answer5: String,
  question6: String,
  answer6: String,
  question7: String,
  answer7: String,
  question8: String,
  answer8: String,
  question9: String,
  answer9: String,
  question10: String,
  answer10: String,
  question11: String,
  answer11: String,
  question12: String,
  answer12: String,
  question13: String,
  answer13: String,
  question14: String,
  answer14: String,
  question15: String,
  answer15: String,
  question16: String,
  answer16: String,
  question17: String,
  answer17: String,
  question18: String,
  answer18: String,
  question19: String,
  answer19: String,
  question20: String,
  answer20: String,
});

let question = mongoose.model('question', QuestionSchema);
module.exports = {
  question: question,
  QuestionSchema: QuestionSchema
};
